title: Stackbit Ampersand Theme
baseURL: /
params:
  description: 'Link4Vets, een platform van dierenartsen voor dierenartsen.'
  layout_style: grid
  palette: green
  header:
    title: Link4Vets
    logo_img: images/l4vlogolong.jpg
    logo_img_alt: Link4Vets Logo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Over Link4vets
        url: /about
        style: link
      - label: Contact
        url: /contact
        style: link
  footer:
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=ampersand&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>.
    has_social: true
    social_links:
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - label: Facebook
        url: lorem-ipsum
        style: icon
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
    has_subscribe: true
    subscribe_title: Schrijf je in voor Updates
    subscribe_content: >-
      Schrijf je in voor onze nieuwsbrief en ontvang maandelijks de
      belangrijkste updates over Link4Vets.
    subscribe_action: /subscribe-success
  favicon: images/clever-mango.jpg
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
